/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_LED_PB_H_INCLUDED
#define PB_LED_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _LedCommand {
    bool has_led_on;
    bool led_on;
} LedCommand;

typedef struct _LedStatus {
    bool led_on;
    char message[32];
} LedStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LedCommand_init_default                  {0, 0}
#define LedStatus_init_default                   {0, ""}
#define LedCommand_init_zero                     {0, 0}
#define LedStatus_init_zero                      {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define LedCommand_has_led_on_tag                1
#define LedCommand_led_on_tag                    2
#define LedStatus_led_on_tag                     1
#define LedStatus_message_tag                    2

/* Struct field encoding specification for nanopb */
#define LedCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_led_on,        1) \
X(a, STATIC,   SINGULAR, BOOL,     led_on,            2)
#define LedCommand_CALLBACK NULL
#define LedCommand_DEFAULT NULL

#define LedStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     led_on,            1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define LedStatus_CALLBACK NULL
#define LedStatus_DEFAULT NULL

extern const pb_msgdesc_t LedCommand_msg;
extern const pb_msgdesc_t LedStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LedCommand_fields &LedCommand_msg
#define LedStatus_fields &LedStatus_msg

/* Maximum encoded size of messages (where known) */
#define LED_PB_H_MAX_SIZE                        LedStatus_size
#define LedCommand_size                          4
#define LedStatus_size                           35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
